<?php
/**
 * Project:  VFP Business Series
 * Copyright: 2014. VFP Business Solutions, LLC
 */

namespace Dandelion\MVC\Application\Controllers\EquipmentHistoryDashboard\Actions;

use Dandelion\MVC\Core\Action;
use Dandelion\MVC\Application\Controllers\EquipmentHistoryDashboard\Models\EquipmentHistoryDashboardViewModel;
use Dandelion\TreeCreator;

require_once MVC_DIR_APP_VIEWS . DIRECTORY_SEPARATOR . 'EquipmentHistoryDashboard' . DIRECTORY_SEPARATOR . 'Model' . DIRECTORY_SEPARATOR . 'EquipmentHistoryDashboardViewModel.php';

/**
 * Class Index
 * @package Dandelion\MVC\Application\Controllers\EquipmentHistoryDashboard\Actions
 */
class Index extends Action
{
    public function PreAction()
    {
        parent::PreAction(); // TODO: Change the autogenerated stub
        $this->Title = "Equipment Dashboard | VFP Business Series";
        $this->Caption = "Equipments";
        $this->Signature = 'EQM';
        $this->ControllerName = $this->Controller;
        $this->FullFeatures = $this->Session->getSessionValue(DASHBOARD_SESSION_PARAM_FULLFEATURES, DASHBOARD_SESSION_PARAM_FULLFEATURES_DEFAULT);
        $this->ShowFiancialDashboard = $this->Session->getSessionValue(DASHBOARD_SESSION_PARAM_SHOWFINANCIALDASHBOARD, DASHBOARD_SESSION_PARAM_SHOWFINANCIALDASHBOARD_DEFAULT);
        $this->CompanyLogo = $this->controller->DatUnitOfWork->ARCOMPRepository->GetCompanyLogo();
        $this->UserName = $this->Session->getSessionValue(DASHBOARD_SESSION_PARAM_USERNAME, DASHBOARD_SESSION_PARAM_USERNAME_DEFAULT);
        $this->User = $this->controller->VfpDataUnitOfWork->SysuserRepository->GetByUsername($this->UserName);
        $this->SavedUserFilters = $this->controller->VfpDataUnitOfWork->SysexportRepository->GetSavedFiltersByUserName($this->User->getUsername(), $this->Signature);
            
    }

    public function Execute()
    {
        $predicate = ""; // TODO: Change for Victor Filter Tree

        $this->CompanyID = $this->controller->DatUnitOfWork->CompanySuffix;
        $this->EquipmentHistoryDashboardViewModelName = EquipmentHistoryDashboardViewModel::getName();
        $this->EquipmentHistoryDashboardFieldsDefinition = EquipmentHistoryDashboardViewModel::getFieldsDefinitionFor($this->CompanyID);

        $this->StatusDictionary = EquipmentHistoryDashboardViewModel::getStatusDictionary();

        $this->FilterId = ''; // TODO: Fetch Saved filter ID for Current User.
        $this->FilterTree = $this->controller->getSessionFilterTree();
        $this->JsonFilterTree = json_encode(TreeCreator::treeToArray($this->FilterTree));

        $this->Page = $this->Session->getSessionValue(DASHBOARD_SESSION_PARAM_PAGE, $this->controller->getDefaultPage());
        $this->OrderBy = $this->Session->getSessionValue(DASHBOARD_SESSION_PARAM_ORDERBY, $this->controller->getDefaultOrderBy($this->EquipmentHistoryDashboardViewModelName));
        $this->Order = $this->Session->getSessionValue(DASHBOARD_SESSION_PARAM_ORDER, $this->controller->getDefaultOrder());
        $this->ItemsPerPage = $this->Session->getSessionValue(DASHBOARD_SESSION_PARAM_ITEMSPERPAGE, $this->Application->getDefaultPagerItemsPerPage());

        $this->Pager = $this->controller->GetPager($this->EquipmentHistoryDashboardViewModelName, $predicate, $this->OrderBy, $this->Order, $this->ItemsPerPage);
        $this->Pager->Paginate();
        $this->ItemCount = $this->Pager->getItemsCount();
        if(!($this->ItemCount > 0)){
            $this->ItemCount = 0;
        }
        $this->Items = $this->Pager->getCurrentPagedItems();

        $viewModels = array();
        foreach ($this->Items as $item) {
            $viewModels [] = new EquipmentHistoryDashboardViewModel($item->ordnum, $item->equipid, $item->itemno, $item->descrip, $item->make, $item->model, $item->serialno, $item->Voltage, $item->EquipType, $item->installdte, $item->expdtein, $item->daterec, $item->status, $item->notes, $item->picture_fi, $item->assettag, $item->locno, $item->qbtxlineid);
        }
        $this->Items = $viewModels;
    }

}